rvm: 2.6.2
node_js: 10.15.3

before_install:
  - ruby -v
  - node -v

install:
  - bundle install --jobs=$(nproc)
  - yarn --frozen-lockfile

script: bundle exec middleman build --verbose

cache:
  yarn: true
