name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Install Nodejs dependencies
        run: yarn
      - name: Run build
        run: NODE_ENV=production BRIDGETOWN_ENV=production yarn deploy
